install.packages("BiocManager")
BiocManager::install("jsonlite")  
BiocManager::install("optparse")
BiocManager::install("curl")
BiocManager::install("httr")
BiocManager::install("withr")
BiocManager::install("biomaRt")
BiocManager::install("edgeR")
BiocManager::install("devtools")
BiocManager::install("igraph")
BiocManager::install("MCL")
BiocManager::install("mclust")

# optional packages for benchmarking step
BiocManager::install("RUVSeq")
BiocManager::install("EDASeq")
BiocManager::install("ggplot2")
BiocManager::install("doParallel")
BiocManager::install("stringi")
